if(BUILD_UNIT_TESTS)
    include(GoogleTest)
    file(GLOB_RECURSE UCMSHARED_TEST_SOURCE_FILES "./case/*.cc")
    if(NOT (RUNTIME_ENVIRONMENT STREQUAL "ascend" OR RUNTIME_ENVIRONMENT STREQUAL "simu"))
        list(FILTER UCMSHARED_TEST_SOURCE_FILES EXCLUDE REGEX ".*[/\\\\]pool[/\\\\].*")
    endif()
    add_executable(ucmshared.test ${UCMSHARED_TEST_SOURCE_FILES})
    target_include_directories(ucmshared.test PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/case)
    target_link_libraries(ucmshared.test PRIVATE
        trans metrics infra_logger
        gtest_main gtest
    )
    if(RUNTIME_ENVIRONMENT STREQUAL "ascend" OR RUNTIME_ENVIRONMENT STREQUAL "simu")
        target_link_libraries(ucmshared.test PRIVATE buffer_pool offset_allocator)
    endif()
    if(RUNTIME_ENVIRONMENT STREQUAL "ascend")
        target_compile_definitions(ucmshared.test PRIVATE UCM_TEST_RUNTIME_ASCEND=1)
    endif()
    gtest_discover_tests(ucmshared.test)
endif()
